"""
PUSHPAK National Corridor Explorer Analytics Module
Provides ranking and network intelligence for India's Top 10 busiest domestic air corridors.
Based on official DGCA (Directorate General of Civil Aviation) Domestic Air Transport Statistics
and PUSHPAK Verified Flight Registry observations.
"""

from typing import List, Dict, Any, Optional

# Defensible Top 10 Indian Domestic Air Corridors
TOP_10_DOMESTIC_CORRIDORS: List[Dict[str, Any]] = [
    {
        "rank": 1,
        "route_code": "DEL-BOM",
        "origin_code": "DEL",
        "destination_code": "BOM",
        "source_city": "Delhi",
        "destination_city": "Mumbai",
        "origin_airport": "Indira Gandhi International Airport (DEL / VIDP)",
        "destination_airport": "Chhatrapati Shivaji Maharaj International Airport (BOM / VABB)",
        "distance_km": 1148,
        "typical_duration_hours": 2.15,
        "typical_duration_str": "2h 10m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)", "Vistara (UK)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "5.5M+ passengers",
        "daily_scheduled_flights_est": "65+ daily frequencies",
        "is_in_representative_basket": True,
        "basket_status": "Included in PUSHPAK Representative Index Basket",
        "basket_weight_pct": 39.92,
        "network_importance": "Primary political-financial axis of India; highest passenger volume corridor.",
        "pricing_characteristics": "Heavy corporate travel mix; extreme walk-up pricing premium during business peaks."
    },
    {
        "rank": 2,
        "route_code": "DEL-BLR",
        "origin_code": "DEL",
        "destination_code": "BLR",
        "source_city": "Delhi",
        "destination_city": "Bengaluru",
        "origin_airport": "Indira Gandhi International Airport (DEL / VIDP)",
        "destination_airport": "Kempegowda International Airport (BLR / VOBL)",
        "distance_km": 1740,
        "typical_duration_hours": 2.75,
        "typical_duration_str": "2h 45m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)", "Vistara (UK)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "4.2M+ passengers",
        "daily_scheduled_flights_est": "50+ daily frequencies",
        "is_in_representative_basket": True,
        "basket_status": "Included in PUSHPAK Representative Index Basket",
        "basket_weight_pct": 40.74,
        "network_importance": "National capital to India's Silicon Valley; high-yield tech corridor.",
        "pricing_characteristics": "Highest flight registry volume in dataset; strong advance booking behavior."
    },
    {
        "rank": 3,
        "route_code": "BOM-BLR",
        "origin_code": "BOM",
        "destination_code": "BLR",
        "source_city": "Mumbai",
        "destination_city": "Bengaluru",
        "origin_airport": "Chhatrapati Shivaji Maharaj International Airport (BOM / VABB)",
        "destination_airport": "Kempegowda International Airport (BLR / VOBL)",
        "distance_km": 842,
        "typical_duration_hours": 1.65,
        "typical_duration_str": "1h 40m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)", "Vistara (UK)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "3.5M+ passengers",
        "daily_scheduled_flights_est": "45+ daily frequencies",
        "is_in_representative_basket": True,
        "basket_status": "Included in PUSHPAK Representative Index Basket",
        "basket_weight_pct": 19.34,
        "network_importance": "Inter-metropolitan financial-technology corridor of Western/Southern India.",
        "pricing_characteristics": "Short-haul high-frequency route with balanced day-return commercial demand."
    },
    {
        "rank": 4,
        "route_code": "DEL-HYD",
        "origin_code": "DEL",
        "destination_code": "HYD",
        "source_city": "Delhi",
        "destination_city": "Hyderabad",
        "origin_airport": "Indira Gandhi International Airport (DEL / VIDP)",
        "destination_airport": "Rajiv Gandhi International Airport (HYD / VOHS)",
        "distance_km": 1258,
        "typical_duration_hours": 2.2,
        "typical_duration_str": "2h 15m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "Vistara (UK)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "2.9M+ passengers",
        "daily_scheduled_flights_est": "38+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Critical corridor connecting North India with the Deccan IT and pharmaceutical hub.",
        "pricing_characteristics": "Competitive carrier capacity; moderate seasonal variation."
    },
    {
        "rank": 5,
        "route_code": "DEL-CCU",
        "origin_code": "DEL",
        "destination_code": "CCU",
        "source_city": "Delhi",
        "destination_city": "Kolkata",
        "origin_airport": "Indira Gandhi International Airport (DEL / VIDP)",
        "destination_airport": "Netaji Subhash Chandra Bose International (CCU / VECC)",
        "distance_km": 1305,
        "typical_duration_hours": 2.25,
        "typical_duration_str": "2h 15m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)"],
        "annual_passenger_volume_est": "2.8M+ passengers",
        "daily_scheduled_flights_est": "35+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Key trunk link connecting the national capital to Eastern and North-Eastern India.",
        "pricing_characteristics": "High festival surge sensitivity (Durga Puja, Diwali) in historical observations."
    },
    {
        "rank": 6,
        "route_code": "BOM-GOI",
        "origin_code": "BOM",
        "destination_code": "GOI",
        "source_city": "Mumbai",
        "destination_city": "Goa (Dabolim/Mopa)",
        "origin_airport": "Chhatrapati Shivaji Maharaj International Airport (BOM / VABB)",
        "destination_airport": "Dabolim Airport / Manohar International Airport Mopa (GOI/GOX)",
        "distance_km": 435,
        "typical_duration_hours": 1.15,
        "typical_duration_str": "1h 10m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "2.4M+ passengers",
        "daily_scheduled_flights_est": "32+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Premier high-density leisure corridor in Western India with dual-airport connectivity.",
        "pricing_characteristics": "High weekend dynamic surge markup; pronounced holiday pricing volatility."
    },
    {
        "rank": 7,
        "route_code": "DEL-MAA",
        "origin_code": "DEL",
        "destination_code": "MAA",
        "source_city": "Delhi",
        "destination_city": "Chennai",
        "origin_airport": "Indira Gandhi International Airport (DEL / VIDP)",
        "destination_airport": "Chennai International Airport (MAA / VOMM)",
        "distance_km": 1756,
        "typical_duration_hours": 2.8,
        "typical_duration_str": "2h 50m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)"],
        "annual_passenger_volume_est": "2.2M+ passengers",
        "daily_scheduled_flights_est": "30+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Long-distance North-South manufacturing and administrative link.",
        "pricing_characteristics": "Stable corporate travel base; moderate advance booking lead times."
    },
    {
        "rank": 8,
        "route_code": "BLR-HYD",
        "origin_code": "BLR",
        "destination_code": "HYD",
        "source_city": "Bengaluru",
        "destination_city": "Hyderabad",
        "origin_airport": "Kempegowda International Airport (BLR / VOBL)",
        "destination_airport": "Rajiv Gandhi International Airport (HYD / VOHS)",
        "distance_km": 505,
        "typical_duration_hours": 1.15,
        "typical_duration_str": "1h 10m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)", "Akasa Air (QP)"],
        "annual_passenger_volume_est": "2.0M+ passengers",
        "daily_scheduled_flights_est": "28+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Key Southern tech shuttle connecting twin innovation hubs.",
        "pricing_characteristics": "High same-day return share; sensitive to high-speed road/rail competition."
    },
    {
        "rank": 9,
        "route_code": "BOM-HYD",
        "origin_code": "BOM",
        "destination_code": "HYD",
        "source_city": "Mumbai",
        "destination_city": "Hyderabad",
        "origin_airport": "Chhatrapati Shivaji Maharaj International Airport (BOM / VABB)",
        "destination_airport": "Rajiv Gandhi International Airport (HYD / VOHS)",
        "distance_km": 620,
        "typical_duration_hours": 1.35,
        "typical_duration_str": "1h 20m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "Vistara (UK)"],
        "annual_passenger_volume_est": "1.9M+ passengers",
        "daily_scheduled_flights_est": "25+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "Commercial connection between Western and South-Central industrial regions.",
        "pricing_characteristics": "Steady commercial business traffic; moderate dispersion."
    },
    {
        "rank": 10,
        "route_code": "BOM-CCU",
        "origin_code": "BOM",
        "destination_code": "CCU",
        "source_city": "Mumbai",
        "destination_city": "Kolkata",
        "origin_airport": "Chhatrapati Shivaji Maharaj International Airport (BOM / VABB)",
        "destination_airport": "Netaji Subhash Chandra Bose International (CCU / VECC)",
        "distance_km": 1660,
        "typical_duration_hours": 2.65,
        "typical_duration_str": "2h 40m",
        "observed_carriers": ["IndiGo (6E)", "Air India (AI)", "SpiceJet (SG)"],
        "annual_passenger_volume_est": "1.8M+ passengers",
        "daily_scheduled_flights_est": "22+ daily frequencies",
        "is_in_representative_basket": False,
        "basket_status": "National Explorer Only",
        "basket_weight_pct": 0.0,
        "network_importance": "East-West cross-continental corridor linking major metropolitan coastal centers.",
        "pricing_characteristics": "Long-distance transcontinental travel with pronounced seasonal swings."
    }
]

def get_top_10_corridors() -> List[Dict[str, Any]]:
    """Returns the ranked Top 10 domestic air corridors."""
    return TOP_10_DOMESTIC_CORRIDORS

def get_corridor_by_code(route_code: str) -> Optional[Dict[str, Any]]:
    """Returns detailed corridor metadata for a specific route code."""
    normalized = route_code.upper().strip()
    for c in TOP_10_DOMESTIC_CORRIDORS:
        if c["route_code"] == normalized:
            return c
    return None
